version: "2"
services:
  boilerplate-api:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/node-rem
    volumes:
      - .:/app
    ports:
      - "3009:3009"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
